### ISSUE TITLE
Investigate why the BundleDeployment being generated in the POM controller has an empty metadata template field

### ISSUE THREAD

**Issue by timflannagan** [openshift/platform-operators#57]
When creating a PlatformOperator resource, a BundleDeployment resource will be generated under-the-hood. For whatever reason, the nested metadata field of that resource's spec.Template field is empty:

```yaml
apiVersion: core.rukpak.io/v1alpha1
kind: BundleDeployment
metadata:
  name: cert-manager
  ownerReferences:
    ...
spec:
  provisionerClassName: core-rukpak-io-plain
  template:
    metadata: {}
    spec:
      provisionerClassName: core-rukpak-io-registry
      source:
        image:
          ref: registry.redhat.io/cert-manager/cert-manager-operator-bundle@sha256:0cb53beabc016e0a3c2358cd3855fb35f37ef27417a955cf07e7668ca44487be
        type: image
```
